export const FIELD_TYPES = [
  { name: 'Symbol', label: 'Short text' },
  { name: 'Text', label: 'Long text' },
  { name: 'RichText', label: 'Rich text' },
  { name: 'Integer', label: 'Integer number' },
  { name: 'Number', label: 'Decimal number' },
  { name: 'Date', label: 'Date and time' },
  { name: 'Location', label: 'Location' },
  { name: 'Asset', label: 'Media' },
  { name: 'Boolean', label: 'Boolean' },
  { name: 'Object', label: 'JSON object' },
  { name: 'Entry', label: 'Reference' },
  { name: 'ResourceLink', label: 'Reference, Different spaces and external sources' },
];

export const FIELD_WIDGETS = [
  { name: 'assetGalleryEditor', label: 'Asset gallery' },
  { name: 'assetLinkEditor', label: 'Asset card' },
  { name: 'assetLinksEditor', label: 'Asset links list' },
  { name: 'boolean', label: 'Radio' },
  { name: 'checkbox', label: 'Checkbox' },
  { name: 'datePicker', label: 'Date picker' },
  { name: 'dropdown', label: 'Dropdown' },
  { name: 'entryCardEditor', label: 'Entry card' },
  { name: 'entryCardsEditor', label: 'Entry cards' },
  { name: 'entryLinkEditor', label: 'Entry link' },
  { name: 'entryLinksEditor', label: 'Entry links list' },
  { name: 'fileEditor', label: 'File' },
  { name: 'listInput', label: 'List' },
  { name: 'locationEditor', label: 'Location' },
  { name: 'markdown', label: 'Markdown' },
  { name: 'multipleLine', label: 'Multiple line' },
  { name: 'numberEditor', label: 'Number editor' },
  { name: 'objectEditor', label: 'Object' },
  { name: 'radio', label: 'Radio' },
  { name: 'rating', label: 'Rating' },
  { name: 'resourceLinkEditor', label: 'Resource card' },
  { name: 'resourceLinksEditor', label: 'Resource card' },
  { name: 'richTextEditor', label: 'RichText' },
  { name: 'singleLine', label: 'Single line' },
  { name: 'slugEditor', label: 'Slug' },
  { name: 'tagEditor', label: 'Tag' },
  { name: 'urlEditor', label: 'URL' },
];
