domainName: sap-air.ctfapps.net
privateKey: ${ssm:/aws/reference/secretsmanager/ci/apps/sap-air-action/prd/private-key}
signingSecret: ${ssm:/aws/reference/secretsmanager/ci/apps/sap-air-action/prd/signing-secret}
