import { autoGeneratedLanguages } from '../util/autoGeneratedLanguages';
import { formatLanguageDisplay } from '../util/languageFormatters';

const AutoGeneratedLanguagesDatalist = () => (
  <datalist id="autogenlanguages">
    {autoGeneratedLanguages.map((lang) => (
      <option key={lang.code} value={formatLanguageDisplay(lang)} />
    ))}
  </datalist>
);

export default AutoGeneratedLanguagesDatalist;
