import { autoGeneratedLanguages } from '../util/autoGeneratedLanguages';

const AutoGeneratedLanguagesDatalist = () => (
  <datalist id="autogenlanguages">
    {autoGeneratedLanguages.map((lang) => (
      <option
        key={lang.code}
        value={`${lang.language}${lang.status === 'Beta' ? ' (' + lang.status + ')' : ''}`}
      />
    ))}
  </datalist>
);

export default AutoGeneratedLanguagesDatalist;
