import tokens from '@contentful/f36-tokens';
import { css } from 'emotion';

export const styles = {
  container: css({
    display: 'flex',
    alignItems: 'baseline',
    whiteSpace: 'nowrap',
    backgroundColor: tokens.gray200,
    borderRadius: tokens.borderRadiusMedium,
    position: 'relative',
    '& #closeButton': {
      opacity: 0,
      pointerEvents: 'none',
      transition: 'opacity 0.2s ease-in-out',
    },
    '&:hover #closeButton': {
      opacity: 1,
      pointerEvents: 'auto',
    },
  }),
  fieldName: css({
    padding: `${tokens.spacing2Xs} ${tokens.spacingXs} ${tokens.spacing2Xs} ${tokens.spacingS}`,
    color: tokens.gray700,
    fontSize: tokens.fontSizeS,
    fontWeight: tokens.fontWeightMedium,
    whiteSpace: 'nowrap',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    margin: 0,
  }),
  operatorDropdownContainer: css({
    display: 'flex',
    alignItems: 'center',
    position: 'relative',
    alignSelf: 'stretch',
    '&::before': {
      content: '""',
      position: 'absolute',
      right: 0,
      top: 0,
      bottom: 0,
      width: '50%',
      backgroundColor: tokens.gray200,
      display: 'block',
      pointerEvents: 'none',
      zIndex: 1,
    },
    '&::after': {
      content: '""',
      position: 'absolute',
      right: 0,
      top: 0,
      bottom: 0,
      width: '50%',
      backgroundColor: tokens.blue500,
      display: 'block',
      pointerEvents: 'none',
      zIndex: 2,
    },
  }),
  operatorDropdown: css({
    display: 'flex',
    alignItems: 'center',
    backgroundColor: tokens.colorWhite,
    borderRadius: 9999,
    fontSize: tokens.fontSizeS,
    fontWeight: tokens.fontWeightMedium,
    padding: `0px ${tokens.spacingS}`,
    color: tokens.blue500,
    position: 'relative',
    userSelect: 'none',
    zIndex: 3,
  }),
  inputContainer: css({
    display: 'flex',
    alignItems: 'center',
    backgroundColor: tokens.blue500,
    overflow: 'hidden',
    minWidth: `100px`,
    maxWidth: `100px`,
    alignSelf: 'stretch',
    borderRadius: `0 ${tokens.borderRadiusMedium} ${tokens.borderRadiusMedium} 0`,
  }),
  inputContainerEmpty: css({
    width: 10,
    backgroundColor: tokens.blue500,
    alignSelf: 'stretch',
    borderRadius: `0 ${tokens.borderRadiusMedium} ${tokens.borderRadiusMedium} 0`,
  }),
  inputButton: css({
    color: tokens.colorWhite,
    fontSize: tokens.fontSizeS,
    fontWeight: tokens.fontWeightMedium,
    backgroundColor: 'transparent',
    border: 'none',
    padding: `0 ${tokens.spacingXs}`,
    width: '100%',
    height: '100%',
    outline: 'none',
    boxShadow: 'none',
    '&:focus': {
      outline: 'none',
      boxShadow: 'none',
    },
    '&::placeholder': {
      color: tokens.colorWhite,
    },
  }),
  input: css({
    fontSize: tokens.fontSizeS,
    fontWeight: tokens.fontWeightMedium,
    backgroundColor: 'transparent',
    color: tokens.colorWhite,
    border: 'none',
    padding: `${tokens.spacing2Xs} ${tokens.spacingS} `,
    width: '100%',
    height: '100%',
    outline: 'none',
    boxShadow: 'none',
    '&:focus': {
      outline: 'none',
      boxShadow: 'none',
    },
    '&::placeholder': {
      color: tokens.colorWhite,
    },
  }),
  closeButton: css({
    position: 'absolute',
    right: -9,
    top: 4,
    width: 18,
    height: 18,
    borderRadius: 1000,
    backgroundColor: tokens.colorWhite,
    boxShadow: `${tokens.boxShadowHeavy}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
};
