variables:
  deploymentPrefix: sls-apps-klaviyo-hosting-test

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - klaviyo-test.ctfapps.net
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [GET, HEAD]
            CachedMethods: [GET, HEAD]
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
          Enabled: true
          HttpVersion: http2
          Origins:
            - DomainName: cf-apps-klaviyo.s3.us-east-1.amazonaws.com
              Id: S3Origin
              OriginPath: /apps/klaviyo-test
          ViewerCertificate:
            MinimumProtocolVersion: TLSv1.2_2021
            AcmCertificateArn: arn:aws:acm:us-east-1:017078452822:certificate/70f5004e-ee05-410d-9391-432b31032f6e
            SslSupportMethod: sni-only
    # Route53Record:
    #   Type: AWS::Route53::RecordSet
    #   Properties:
    #     HostedZoneName: ${self:custom.hostedZoneName}
    #     Name: ${self:custom.domainName}
    #     Type: CNAME
    #     TTL: 300
    #     ResourceRecords:
    #       - !GetAtt CloudFrontDistribution.DomainName
          