variables:

resources:
  Resources:
    KlaviyoBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cf-apps-klaviyo-test
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true