import { FC, useEffect, useRef, useState } from 'react';
import {
  Box,
  Button,
  Checkbox,
  Flex,
  FormControl,
  IconButton,
  Select,
  Subheading,
  Table,
  TextInput,
  Textarea,
} from '@contentful/f36-components';
import { DeleteIcon, PlusIcon } from '@contentful/f36-icons';
import {
  QUESTION_ANSWER_MODES,
  QuestionRow,
  ReplacementRow,
  RobotsAssetContext,
  RobotsParamField,
  RobotsParamSection,
  TaxonomyRow,
  asTaxonomyValue,
  emptyQuestionRow,
  emptyTaxonomyRow,
  groupFieldsBySection,
  isFieldVisible,
} from '../../util/robotsCatalog';
import { Track } from '../../util/types';
import { autoGeneratedLanguages } from '../../util/autoGeneratedLanguages';
import { formatLanguageDisplay } from '../../util/languageFormatters';

/**
 * Renders one workflow's parameters from its catalog descriptor.
 *
 * Generic on purpose: `ask-questions`, `moderate` and `find-key-moments` need genuinely richer
 * forms than a language picker, and hand-writing a form per workflow would mean twelve components
 * that drift. Nested Mux parameters are addressed by dotted path (`thresholds.sexual`), flattened
 * here and re-nested by `buildRobotsParameters`.
 */

interface RobotsParamFieldsProps {
  fields: RobotsParamField[];
  values: Record<string, unknown>;
  onChange: (name: string, value: unknown) => void;
  /** Existing asset tracks, for `track`-kind parameters. */
  captions: Track[];
  audioTracks: Track[];
  /**
   * What is known about the asset. A `showWhen` can key off this as well as off another field, so
   * a parameter the reference says is ignored for this kind of asset is simply not offered.
   */
  context?: RobotsAssetContext;
}

const LANGUAGE_DATALIST_ID = 'robots-language-codes';

const RobotsParamFields: FC<RobotsParamFieldsProps> = ({
  fields,
  values,
  onChange,
  captions,
  audioTracks,
  context,
}) => {
  if (fields.length === 0) {
    return (
      <Box marginTop="spacingS">
        <FormControl.HelpText>This workflow takes no options.</FormControl.HelpText>
      </Box>
    );
  }

  const needsLanguageDatalist = fields.some((field) => field.kind === 'language');

  const renderField = (field: RobotsParamField) => (
    <ParamField
      key={field.name}
      field={field}
      value={values[field.name]}
      onChange={onChange}
      captions={captions}
      audioTracks={audioTracks}
    />
  );

  return (
    <>
      {needsLanguageDatalist && (
        <datalist id={LANGUAGE_DATALIST_ID}>
          {autoGeneratedLanguages.map((language) => (
            <option key={language.code} value={language.code}>
              {formatLanguageDisplay(language)}
            </option>
          ))}
        </datalist>
      )}
      {/* A `showWhen` field is hidden *and* unsent when its condition is not met — see
          `isFieldVisible`. Keeping both halves keyed off the same predicate is what stops the
          form showing one request and sending another. */}
      {groupFieldsBySection(fields.filter((field) => isFieldVisible(field, values, context))).map(
        (group) =>
          group.section ? (
            <ParamSection key={group.section.id} section={group.section}>
              {group.fields.map(renderField)}
            </ParamSection>
          ) : (
            group.fields.map(renderField)
          )
      )}
    </>
  );
};

const ParamSection: FC<{ section: RobotsParamSection; children: React.ReactNode }> = ({
  section,
  children,
}) => {
  const headingId = `robots-section-${section.id}`;
  return (
    <Box
      role="group"
      aria-labelledby={headingId}
      marginTop="spacingL"
      marginBottom="spacingL"
      data-testid={headingId}>
      <Subheading id={headingId} marginBottom="spacingXs">
        {section.title}
      </Subheading>
      {section.description && (
        <Box marginBottom="spacingS">
          <FormControl.HelpText>{section.description}</FormControl.HelpText>
        </Box>
      )}
      {children}
    </Box>
  );
};

interface ParamFieldProps {
  field: RobotsParamField;
  value: unknown;
  onChange: (name: string, value: unknown) => void;
  captions: Track[];
  audioTracks: Track[];
}

const ParamField: FC<ParamFieldProps> = ({ field, value, onChange, captions, audioTracks }) => {
  // The id belongs on FormControl: that is what F36 turns into the label's `htmlFor` and passes
  // down to the control, so a label with no associated input is a real a11y defect, not just an
  // awkward test.
  const control = (children: React.ReactNode) => (
    <FormControl
      id={`robots-param-${field.name}`}
      isRequired={field.isRequired}
      marginBottom="spacingM">
      <FormControl.Label>{field.label}</FormControl.Label>
      {children}
      {field.helpText && <FormControl.HelpText>{field.helpText}</FormControl.HelpText>}
    </FormControl>
  );

  switch (field.kind) {
    case 'boolean': {
      const checked = value === undefined ? !!field.defaultValue : !!value;
      return (
        <Box marginBottom="spacingM">
          <Checkbox
            id={`robots-param-${field.name}`}
            isChecked={checked}
            helpText={field.helpText}
            onChange={(event) => onChange(field.name, (event.target as HTMLInputElement).checked)}>
            {field.label}
          </Checkbox>
        </Box>
      );
    }

    case 'select':
      return control(
        <Select
          value={(value as string) ?? (field.defaultValue as string) ?? ''}
          onChange={(event) => onChange(field.name, (event.target as HTMLSelectElement).value)}>
          {(field.options ?? []).map((option) => (
            <Select.Option key={option.value} value={option.value}>
              {option.label}
            </Select.Option>
          ))}
        </Select>
      );

    case 'number':
      return control(
        <TextInput
          type="number"
          min={field.min}
          max={field.max}
          step={field.step}
          value={value === undefined ? '' : String(value)}
          onChange={(event) => {
            const raw = (event.target as HTMLInputElement).value;
            // Empty means "leave this parameter out", not zero.
            onChange(field.name, raw === '' ? undefined : Number(raw));
          }}
        />
      );

    case 'language':
      return control(
        <TextInput
          list={LANGUAGE_DATALIST_ID}
          placeholder={field.placeholder ?? 'en'}
          value={(value as string) ?? ''}
          onChange={(event) => onChange(field.name, (event.target as HTMLInputElement).value)}
        />
      );

    case 'track': {
      const tracks = field.trackType === 'audio' ? audioTracks : captions;
      if (tracks.length === 0) {
        return control(
          <FormControl.ValidationMessage>
            This asset has no {field.trackType === 'audio' ? 'audio' : 'caption'} track to use.
          </FormControl.ValidationMessage>
        );
      }
      return control(
        <Select
          value={(value as string) ?? ''}
          onChange={(event) => onChange(field.name, (event.target as HTMLSelectElement).value)}>
          <Select.Option value="">Select a track</Select.Option>
          {tracks.map((track) => (
            <Select.Option key={track.id} value={track.id}>
              {[track.name, track.language_code].filter(Boolean).join(' · ') || track.id}
            </Select.Option>
          ))}
        </Select>
      );
    }

    case 'textarea':
      return control(
        <Textarea
          rows={3}
          value={(value as string) ?? ''}
          onChange={(event) => onChange(field.name, (event.target as HTMLTextAreaElement).value)}
        />
      );

    case 'stringList':
      return control(<StringListInput field={field} value={value} onChange={onChange} />);

    case 'enumList': {
      const selected = Array.isArray(value) ? (value as string[]) : [];
      // No cap enforced here on purpose. `maxItems` is checked by `validateParams`, which can say
      // which field is over and by how much; a control that silently refuses a click explains
      // nothing — the same lesson as the `stringList` truncation this widget replaced. It is
      // also unreachable today: the one capped enum (`rubric_priorities`, max 4) has exactly four
      // members, so clicking cannot exceed it.
      return control(
        <>
          {(field.options ?? []).map((option) => {
            const isChecked = selected.includes(option.value);
            return (
              <Checkbox
                key={option.value}
                id={`robots-param-${field.name}-${option.value}`}
                isChecked={isChecked}
                onChange={(event) => {
                  const next = (event.target as HTMLInputElement).checked
                    ? [...selected, option.value]
                    : selected.filter((current) => current !== option.value);
                  onChange(field.name, next);
                }}>
                {option.label}
              </Checkbox>
            );
          })}
          {field.maxItems !== undefined && (
            <FormControl.HelpText>
              {selected.length} of {field.maxItems} chosen.
            </FormControl.HelpText>
          )}
        </>
      );
    }

    case 'questions': {
      const rows: QuestionRow[] = Array.isArray(value)
        ? (value as QuestionRow[])
        : [emptyQuestionRow()];
      const update = (next: QuestionRow[]) => onChange(field.name, next);
      const patch = (index: number, changes: Partial<QuestionRow>) =>
        update(rows.map((existing, i) => (i === index ? { ...existing, ...changes } : existing)));
      return control(
        <>
          <Table verticalAlign="middle">
            <Table.Head>
              <Table.Row>
                <Table.Cell>Question</Table.Cell>
                <Table.Cell>Answered</Table.Cell>
                <Table.Cell>Answer options</Table.Cell>
                <Table.Cell />
              </Table.Row>
            </Table.Head>
            <Table.Body>
              {rows.map((row, index) => {
                const isFreeForm = row.answerMode === 'free_form';
                return (
                  <Table.Row key={index}>
                    <Table.Cell>
                      <TextInput
                        aria-label={`Question ${index + 1}`}
                        value={row.question}
                        onChange={(event) =>
                          patch(index, { question: (event.target as HTMLInputElement).value })
                        }
                      />
                    </Table.Cell>
                    <Table.Cell>
                      {/* A mode rather than two boxes: `answer_options` and `free_form_reply`
                          are mutually exclusive, and an empty options box has to be able to mean
                          the documented yes / no default *and* nothing else. */}
                      <Select
                        aria-label={`How question ${index + 1} is answered`}
                        value={row.answerMode ?? 'options'}
                        onChange={(event) =>
                          patch(index, {
                            answerMode: (event.target as HTMLSelectElement)
                              .value as QuestionRow['answerMode'],
                          })
                        }>
                        {QUESTION_ANSWER_MODES.map((mode) => (
                          <Select.Option key={mode.value} value={mode.value}>
                            {mode.label}
                          </Select.Option>
                        ))}
                      </Select>
                    </Table.Cell>
                    <Table.Cell>
                      <TextInput
                        aria-label={`Answer options for question ${index + 1}`}
                        placeholder={isFreeForm ? 'Not used' : 'yes, no'}
                        isDisabled={isFreeForm}
                        value={isFreeForm ? '' : row.answerOptions}
                        onChange={(event) =>
                          patch(index, {
                            answerOptions: (event.target as HTMLInputElement).value,
                          })
                        }
                      />
                    </Table.Cell>
                    <Table.Cell>
                      <IconButton
                        variant="transparent"
                        aria-label={`Remove question ${index + 1}`}
                        icon={<DeleteIcon />}
                        isDisabled={rows.length === 1}
                        onClick={() => update(rows.filter((_, i) => i !== index))}
                      />
                    </Table.Cell>
                  </Table.Row>
                );
              })}
            </Table.Body>
          </Table>
          <Box marginTop="spacingS">
            <Button
              size="small"
              variant="secondary"
              startIcon={<PlusIcon />}
              onClick={() => update([...rows, emptyQuestionRow()])}>
              Add question
            </Button>
          </Box>
        </>
      );
    }

    case 'replacements': {
      const rows: ReplacementRow[] = Array.isArray(value) ? (value as ReplacementRow[]) : [];
      const update = (next: ReplacementRow[]) => onChange(field.name, next);
      return control(
        <>
          {rows.length > 0 && (
            <Table verticalAlign="middle">
              <Table.Head>
                <Table.Row>
                  <Table.Cell>Find</Table.Cell>
                  <Table.Cell>Replace with</Table.Cell>
                  <Table.Cell align="center">Case sensitive</Table.Cell>
                  <Table.Cell />
                </Table.Row>
              </Table.Head>
              <Table.Body>
                {rows.map((row, index) => (
                  <Table.Row key={index}>
                    <Table.Cell>
                      <TextInput
                        aria-label={`Find text ${index + 1}`}
                        value={row.find}
                        onChange={(event) =>
                          update(
                            rows.map((existing, i) =>
                              i === index
                                ? { ...existing, find: (event.target as HTMLInputElement).value }
                                : existing
                            )
                          )
                        }
                      />
                    </Table.Cell>
                    <Table.Cell>
                      <TextInput
                        aria-label={`Replacement text ${index + 1}`}
                        value={row.replace}
                        onChange={(event) =>
                          update(
                            rows.map((existing, i) =>
                              i === index
                                ? {
                                    ...existing,
                                    replace: (event.target as HTMLInputElement).value,
                                  }
                                : existing
                            )
                          )
                        }
                      />
                    </Table.Cell>
                    <Table.Cell align="center">
                      {/* F36's Checkbox is a full-width column that pins its box to the left, so
                          the cell's own alignment cannot centre it; this wrapper can. */}
                      <Flex justifyContent="center">
                        <Checkbox
                          id={`robots-replacement-case-${index}`}
                          aria-label={`Case sensitive ${index + 1}`}
                          isChecked={row.caseSensitive}
                          onChange={(event) =>
                            update(
                              rows.map((existing, i) =>
                                i === index
                                  ? {
                                      ...existing,
                                      caseSensitive: (event.target as HTMLInputElement).checked,
                                    }
                                  : existing
                              )
                            )
                          }
                        />
                      </Flex>
                    </Table.Cell>
                    <Table.Cell>
                      <IconButton
                        variant="transparent"
                        aria-label={`Remove replacement ${index + 1}`}
                        icon={<DeleteIcon />}
                        onClick={() => update(rows.filter((_, i) => i !== index))}
                      />
                    </Table.Cell>
                  </Table.Row>
                ))}
              </Table.Body>
            </Table>
          )}
          <Box marginTop="spacingS">
            <Button
              size="small"
              variant="secondary"
              startIcon={<PlusIcon />}
              onClick={() => update([...rows, { find: '', replace: '', caseSensitive: false }])}>
              Add replacement
            </Button>
          </Box>
        </>
      );
    }

    case 'taxonomy':
      return control(<TaxonomyInput field={field} value={value} onChange={onChange} />);

    case 'text':
    default:
      return control(
        <Flex>
          <TextInput
            id={`robots-param-${field.name}`}
            placeholder={field.placeholder}
            value={(value as string) ?? ''}
            onChange={(event) => onChange(field.name, (event.target as HTMLInputElement).value)}
          />
        </Flex>
      );
  }
};

/**
 * The `taxonomy` widget: a name, a table of values, and what to do with anything outside them.
 *
 * Full width and inline rather than behind a collapse. The whole object is one form value — see
 * `TaxonomyValue` — so every control here patches the same object rather than owning a dotted
 * path of its own, which is what lets the field be sent or omitted as a unit.
 */
const TaxonomyInput: FC<{
  field: RobotsParamField;
  value: unknown;
  onChange: (name: string, value: unknown) => void;
}> = ({ field, value, onChange }) => {
  const taxonomy = asTaxonomyValue(value);
  const rows = taxonomy.values;
  const patch = (changes: Partial<typeof taxonomy>) =>
    onChange(field.name, { ...taxonomy, ...changes });
  const patchRow = (index: number, changes: Partial<TaxonomyRow>) =>
    patch({
      values: rows.map((existing, i) => (i === index ? { ...existing, ...changes } : existing)),
    });

  return (
    <>
      <FormControl id={`robots-param-${field.name}-name`} marginBottom="spacingS">
        <FormControl.Label>Taxonomy name</FormControl.Label>
        <TextInput
          placeholder="Content pillars"
          value={taxonomy.name}
          onChange={(event) => patch({ name: (event.target as HTMLInputElement).value })}
        />
      </FormControl>

      {rows.length > 0 && (
        <Table verticalAlign="middle">
          <Table.Head>
            <Table.Row>
              <Table.Cell>Value</Table.Cell>
              <Table.Cell>When it applies</Table.Cell>
              <Table.Cell>Also known as</Table.Cell>
              <Table.Cell />
            </Table.Row>
          </Table.Head>
          <Table.Body>
            {rows.map((row, index) => (
              <Table.Row key={index}>
                <Table.Cell>
                  <TextInput
                    aria-label={`Taxonomy value ${index + 1}`}
                    value={row.label}
                    onChange={(event) =>
                      patchRow(index, { label: (event.target as HTMLInputElement).value })
                    }
                  />
                </Table.Cell>
                <Table.Cell>
                  <TextInput
                    aria-label={`Description for taxonomy value ${index + 1}`}
                    value={row.description}
                    onChange={(event) =>
                      patchRow(index, { description: (event.target as HTMLInputElement).value })
                    }
                  />
                </Table.Cell>
                <Table.Cell>
                  <TextInput
                    aria-label={`Aliases for taxonomy value ${index + 1}`}
                    placeholder="comma, separated"
                    value={row.aliases}
                    onChange={(event) =>
                      patchRow(index, { aliases: (event.target as HTMLInputElement).value })
                    }
                  />
                </Table.Cell>
                <Table.Cell>
                  <IconButton
                    variant="transparent"
                    aria-label={`Remove taxonomy value ${index + 1}`}
                    icon={<DeleteIcon />}
                    onClick={() => patch({ values: rows.filter((_, i) => i !== index) })}
                  />
                </Table.Cell>
              </Table.Row>
            ))}
          </Table.Body>
        </Table>
      )}

      <Box marginTop="spacingS" marginBottom="spacingS">
        <Button
          size="small"
          variant="secondary"
          startIcon={<PlusIcon />}
          onClick={() => patch({ values: [...rows, emptyTaxonomyRow()] })}>
          Add value
        </Button>
        {field.taxonomyLimits?.maxValues !== undefined && (
          <FormControl.HelpText>
            {rows.length} of {field.taxonomyLimits.maxValues} used.
          </FormControl.HelpText>
        )}
      </Box>

      {/* A checkbox rather than a select with a "No preference" member: the API rejects the
          taxonomy object unless `allow_other` is a boolean, so there is no third outcome to
          offer. Checked by default — see `TaxonomyValue`. */}
      <Box marginBottom="none">
        <Checkbox
          id={`robots-param-${field.name}-allow-other`}
          isChecked={taxonomy.allowOther}
          helpText="Clear this to restrict the output to the values above and their aliases."
          onChange={(event) => patch({ allowOther: (event.target as HTMLInputElement).checked })}>
          Allow values outside this list
        </Checkbox>
      </Box>
    </>
  );
};

/**
 * Splits the textarea into list items: one per line, outer whitespace trimmed, blanks dropped.
 *
 * Trims the *ends* only. These parameters take phrases, not words — `always_censor` and
 * `never_censor` are documented as "words/phrases", `phrases` is capped at five words, and
 * `never_translate`'s only character rule names `<`, `>`, invisible characters and anything
 * Unicode normalisation alters. Interior spaces are legal everywhere they are used.
 */
const splitStringList = (text: string): string[] =>
  text
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean);

/**
 * The `stringList` widget.
 *
 * The bug this exists to fix: the textarea was controlled directly off the parsed array
 * (`value={items.join('\n')}`) while `onChange` parsed, trimmed, filtered and `slice`d every
 * keystroke. So the normalised text was pushed straight back into the box the editor was typing
 * in, and the normalisation ate their input as they went — a space keyed at the end of a word was
 * trimmed away before it could be followed by another word, a newline was a blank line and got
 * `filter(Boolean)`'d out before a second item could be started, and `maxItemLength` `slice`d
 * mid-word so a long entry could not be edited at all, only retyped shorter. Three symptoms, one
 * cause: normalising the *displayed* value.
 *
 * Fixed by keeping the raw text the editor typed and normalising only what leaves. The caps are
 * enforced by `validateParams` instead, which can name the offending entry rather than silently
 * truncating it.
 */
const StringListInput: FC<{
  field: RobotsParamField;
  value: unknown;
  onChange: (name: string, value: unknown) => void;
}> = ({ field, value, onChange }) => {
  const items = Array.isArray(value) ? (value as string[]) : [];
  const committed = items.join('\n');
  const [draft, setDraft] = useState(committed);
  const draftRef = useRef(draft);
  draftRef.current = draft;

  // Re-seed only when the value changed somewhere else — a workflow switch, or the modal's reset.
  // Comparing against what this draft *would* produce is what keeps it from clobbering the
  // trailing space or blank line the editor is in the middle of typing.
  useEffect(() => {
    if (splitStringList(draftRef.current).join('\n') !== committed) setDraft(committed);
  }, [committed]);

  return (
    <>
      <Textarea
        rows={2}
        placeholder="One per line"
        value={draft}
        onChange={(event) => {
          const raw = (event.target as HTMLTextAreaElement).value;
          setDraft(raw);
          onChange(field.name, splitStringList(raw));
        }}
      />
      {!!field.maxItems && (
        <FormControl.HelpText>
          {items.length} of {field.maxItems} used.
        </FormControl.HelpText>
      )}
    </>
  );
};

export default RobotsParamFields;
