const rewritePrompt = (
  prompt: string,
  rewriteActions: string
) => `You are editing content generated by someone else, and need to rewrite the following text using the following constraints/tonal shifts: "${rewriteActions}". Keep in mind that the constraints can be categorized in the following ways: tone changes, adjustments, edits, emulating certain writing styles, and so on.  Use your best judgement in editing the article given the list of constraints. Your job is to just rewrite the content and not expand it, keeping the word count of the generated text similar to the word count of the original content, unless if the constraints listed includes longer. You cannot produce content that is longer in word count than the content quoted below unless if the constraints listed includes longer
  "${prompt}"`;

export default rewritePrompt;
