# https://dependabot.com/docs/config-file/#dependabot-config-files
version: 1
update_configs:
  - package_manager: "docker"
    directory: "/.circleci"
    update_schedule: "weekly"
    commit_message:
      prefix: "update"
      include_scope: true
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
