export type LanguageStatus = 'Stable' | 'Beta';

export interface Language {
  language: string;
  code: string;
  status: LanguageStatus;
}

export const autoGeneratedLanguages: Language[] = [
  { language: 'English', code: 'en', status: 'Stable' },
  { language: 'Spanish', code: 'es', status: 'Stable' },
  { language: 'Italian', code: 'it', status: 'Stable' },
  { language: 'Portuguese', code: 'pt', status: 'Stable' },
  { language: 'German', code: 'de', status: 'Stable' },
  { language: 'French', code: 'fr', status: 'Stable' },
  { language: 'Polish', code: 'pl', status: 'Beta' },
  { language: 'Russian', code: 'ru', status: 'Beta' },
  { language: 'Dutch', code: 'nl', status: 'Beta' },
  { language: 'Catalan', code: 'ca', status: 'Beta' },
  { language: 'Turkish', code: 'tr', status: 'Beta' },
  { language: 'Swedish', code: 'sv', status: 'Beta' },
  { language: 'Ukrainian', code: 'uk', status: 'Beta' },
  { language: 'Norwegian', code: 'no', status: 'Beta' },
  { language: 'Finnish', code: 'fi', status: 'Beta' },
  { language: 'Slovak', code: 'sk', status: 'Beta' },
  { language: 'Greek', code: 'el', status: 'Beta' },
  { language: 'Czech', code: 'cs', status: 'Beta' },
  { language: 'Croatian', code: 'hr', status: 'Beta' },
  { language: 'Danish', code: 'da', status: 'Beta' },
  { language: 'Romanian', code: 'ro', status: 'Beta' },
  { language: 'Bulgarian', code: 'bg', status: 'Beta' },
];
