import { Language } from './autoGeneratedLanguages';

export const formatLanguageDisplay = (language: Language): string => {
  return language.status === 'Beta' ? `${language.language} (Beta)` : language.language;
};

export const findLanguageByDisplayName = (
  languages: Language[],
  displayName: string
): Language | undefined => {
  return languages.find((lang) => formatLanguageDisplay(lang) === displayName);
};
