name: Deploy SFCC Contentful App

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'apps/salesforce-commerce-cloud/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/salesforce-commerce-cloud

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: apps/salesforce-commerce-cloud/package-lock.json

      - run: npm ci

      - run: npm run build

      - run: npm run deploy
        env:
          CONTENTFUL_ORG_ID: ${{ secrets.CONTENTFUL_ORG_ID }}
          CONTENTFUL_APP_DEF_ID: ${{ secrets.CONTENTFUL_APP_DEF_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
